
#This is a template to build your own project with the e-puck2_main-processor folder as a library.
#Simply adapt the lines below to be able to compile

# Define project name here
PROJECT = MiniProject

#Define path to the e-puck2_main-processor folder
GLOBAL_PATH = ../e-puck2_main-processor

CHIBIOS = ../e-puck2_main-processor/ChibiOS

#Source files to include
CSRC += ./main.c \
		./travel.c \
		./detection.c


#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile